# Generated by Django 3.1.1 on 2020-10-06 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='createdon',
            new_name='completedon',
        ),
    ]
